/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import React from 'react'

import { Profile } from '@/components/Profile'

export default function Home() {
	return (
		<>
			<Head>
				<title>Lear Nextjs</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="./favicon.ico" />
				<script src="/engpush.js"></script>
				<script src="https://engpush.takuhai-rental.com/assets/js/engpush.js" defer></script>
				<script src="https://engpush.takuhai-rental.com/assets/js/EngPushSDK.sw.js" defer></script>
			</Head>
			<div>
				<h1>My Profile: asd 3333</h1>

				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
				<Profile />
			</div>
		</>
	)
}
